### ISSUE TITLE
the app for pyqt5

### ISSUE THREAD

**Issue by wlzxzq** [Wanderson-Magalhaes/PyOneDark_Qt_Widgets_Modern_GUI#1]
https://drive.google.com/file/d/1TGqgcWaBIeQJMNEo88FfADSE-rIE-RBC/view?usp=sharing
i can not get the button's sender

**Comment by wlzxzq** [comment]
> https://drive.google.com/file/d/1TGqgcWaBIeQJMNEo88FfADSE-rIE-RBC/view?usp=sharing
> 我无法获取按钮的发件人

I have overcome this!

**Comment by wuqua** [comment]
> 

Can you tell me how solve the problem？Thanks.

**Comment by wuqua** [comment]
Could you tell me how sovle the problem for pyqt5?

**Comment by Oceanapart00** [comment]
我碰到了一样的问题，请问你是这么解决的
I have encountered the same problem. May I ask how you solved it
